### ISSUE TITLE
Emojis translates wrong or becomes "?"

### ISSUE THREAD

**Issue by MonzUn** [Eco-DiscordLink/EcoDiscordPlugin#1]
Most emojis are either translated to ? or some other emoji when sent from Discord to Eco.

**Comment by MonzUn** [comment]
New issues page at https://github.com/Eco-DiscordLink/EcoDiscordPlugin/issues

**Comment by Dave247** [comment]
While I'm no modder/programmer myself so my knowledge on the topic would be limited, I don't see there to be any easy or good way to properly do something about this. You might need to end up having to manually map emoji's sent from Discord into their Eco counterpoints (and vice versa) for it to work correctly, and for everything else have the bot/mod set to ignore and not include the emoji text so to not display incorrectly.

**Comment by MonzUn** [comment]
On top of that; simply identifying text of the wrong encoding and ALSO finding an emoji in there, seems to be really tricky.

**Comment by Dave247** [comment]
Also I'm not sure how useful it would be (if at all), but here is the repo for a Space Engineers plugin (that uses another larger mod) that sends chat messages between Discord and the game.
https://github.com/Bishbash777/SEDB-RELOADED
