### ISSUE TITLE
discordlink configurationfile

### ISSUE THREAD

**Issue by Mdye99** [Eco-DiscordLink/EcoDiscordPlugin#102]
the channel linking configuration mentions adding a discord channel and the corresponding eco channel and direction etc. but the sample from the config does not actual have all that information. so i'm just wondering where i can find a sample that has that setup

**Comment by MonzUn** [comment]
Hello and apologies for responding late.
Could you point out specifically where this information is missing?

Here's the sample from the example containing that information taken from here
https://github.com/Eco-DiscordLink/EcoDiscordPlugin/blob/develop/ConfigurationNoGUI.md#linking-chat-channels
```
  "ChatChannelLinks": [  
   {  
    "AllowUserMentions": true,  
    "AllowRoleMentions": true,  
    "AllowChannelMentions": true,  
    "Direction": "Duplex",  
    "HereAndEveryoneMentionPermission": "Forbidden",  
    "EcoChannel": "General",  
    "DiscordChannelId": 980963363205025815,  
    "UseTimestamp": true  
   }  
  ],  
```

**Comment by Mdye99** [comment]
https://github.com/Eco-DiscordLink/EcoDiscordPlugin/blob/develop/ConfigurationNoGUI.md#linking-chat-channels
![image](https://github.com/user-attachments/assets/fedb1952-fc9c-441d-aa1f-105e677e842a)

it says:
2. Set the "DiscordChannelId" field to the ID of the Discord channel you wish to synchronize with a channel in Eco.
3. Set the "EcoChannel" field to the name of the Eco channel you wish to synchronize with the Discord channel in the previous step.

but the config template doesn't have those 2 fields
![image](https://github.com/user-attachments/assets/c723e343-5488-4547-96c7-5fb2b3791345)

**Comment by MonzUn** [comment]
What's in your screenshot is the template, not the sample config.
The sample config is just above the text you quoted.
