### ISSUE TITLE
Exception: System.MissingMethodException: Method not found: 'Boolean Eco.Gameplay.Disasters.DisasterPlugin.get_MeteorDestroyed()'.

### ISSUE THREAD

**Issue by Mdye99** [Eco-DiscordLink/EcoDiscordPlugin#103]
please help.

![image](https://github.com/user-attachments/assets/95471437-af0c-492f-b6a4-8799917751b9)

**Comment by MonzUn** [comment]
The solution for this issue is to update DiscordLink to a version that is compatible with Eco, or to run a version of Eco that is compatible with your current version of DiscordLink.
