### ISSUE TITLE
bug wont save nor display address

### ISSUE THREAD

**Issue by andsim** [Eco-DiscordLink/EcoDiscordPlugin#13]
i have disabled meteor on the server as well discordlink setting but it not disabled as i see still seeing count down time and server address wont display.

`
  "DiscordCommandPrefix": "?",
  "EcoStatusDiscordChannels": [
    {
      "DiscordGuild": "Andsim-Gaming-tv",
      "DiscordChannel": "eco-status",
      "UseName": true,
      "UseDescription": false,
      "UseLogo": true,
      "UseAddress": true,
      "UsePlayerCount": true,
      "UsePlayerList": true,
      "UseTimeSinceStart": true,
      "UseTimeRemaining": false,
      "UseMeteorHasHit": false
    }
  ],
  "ServerName": "Andsim Eco Gaming",
  "ServerDescription": "The place to play Eco!",
  "ServerIP": "ecoserver.andsimgaming.ca:3000",
  "ServerLogo": "http://github.com/Spoffy/EcoDiscordPlugin/raw/master/images/DiscordLinkLogo_Nameless.png",
  "ChatChannelLinks": [
    {
      "DiscordGuild": "Andsim-Gaming-tv",
      "DiscordChannel": "eco",
      "EcoChannel": "General",
      "AllowUserMentions": true,
      "AllowRoleMentions": true,
      "AllowChannelMentions": true
    },
  ],
  "Debug": false,
  "LogChat": false,
  "ChatlogPath": "../Chatlog.txt",
  "EcoCommandChannel": "general",
  "InviteMessage": "Join us on Discord!\n[LINK]"
}`
i left out bottoken
here picture
![image](https://user-images.githubusercontent.com/831158/93005520-b9e7f800-f51f-11ea-8140-e59583a25a0c.png)

**Comment by andsim** [comment]
os debain 9.13

**Comment by MonzUn** [comment]
The server address issue is an error in the default config. Upcoming releases have it fixed but I'm yet to release it.
"ServerIP" should be "ServerAddress".

How did you generate this status message?
Was it via ?EcoStatus or was it generated by the EcoStatusChannel feature?

The command isn't configurable, but the status channel should not print the time remaining in this case and that is a bug in that case.

**Comment by andsim** [comment]
was it by ?EcoStatus

**Comment by andsim** [comment]
ok
here i see  i rename that line to ServerAddress
![image](https://user-images.githubusercontent.com/831158/93105633-4fe56500-f67d-11ea-815f-86fea8558b9d.png)

**Comment by MonzUn** [comment]
> was it by ?EcoStatus

What does this mean?

**Comment by andsim** [comment]
meteor time is still active when i use that /ecostastus

**Comment by MonzUn** [comment]
That is the intended behaviour.
You have configured the live status display, not the ?EcoStatus command.
the ?ecostatus command is not configurable.
