### ISSUE TITLE
2.1.0 Playerlist option should have server name

### ISSUE THREAD

**Issue by MishkaFur** [Eco-DiscordLink/EcoDiscordPlugin#20]
2.1.0 Playerlist option should have the ability to have server name

For example a single discord has multiple servers but only wants one status channel.

![image](https://user-images.githubusercontent.com/61889138/96253622-dd351580-0fab-11eb-9621-f522daf400b3.png)

**Comment by MonzUn** [comment]
I will either enable the player list to be appended at the end of server info, or add an option for showing the name in the player list.

**Comment by MonzUn** [comment]
All info displays have been given footers like this one.
![image](https://user-images.githubusercontent.com/11805935/99197139-d9ee9e80-2790-11eb-9e91-2b8c4c40f3e6.png)

This feature will be in an upcoming release.
