### ISSUE TITLE
2.1.0 Trades should specify account/store name

### ISSUE THREAD

**Issue by MishkaFur** [Eco-DiscordLink/EcoDiscordPlugin#21]
Trades output should specify the account/store name

![image](https://user-images.githubusercontent.com/61889138/96276669-39f3f880-0fcb-11eb-9572-1d9ad3a58259.png)

![image](https://user-images.githubusercontent.com/61889138/96276692-40827000-0fcb-11eb-9fda-55209eab6d19.png)

**Comment by MonzUn** [comment]
I have deliberately left this out in order to make the messages as short as possible.
What is your use case for this? Is it information that you often need?

**Comment by MishkaFur** [comment]
A player who is manager of a bank account, it is showing the trade as whoever owns the plot when it might be actually paying an account which is owned by a group 

![image](https://user-images.githubusercontent.com/61889138/96323276-57998000-1014-11eb-85cb-5496155ec33c.png)

![image](https://user-images.githubusercontent.com/61889138/96323283-5e27f780-1014-11eb-89ea-97c5e404de24.png)

![image](https://user-images.githubusercontent.com/61889138/96323299-6ed86d80-1014-11eb-8ad0-1aca4a56b5ee.png)

**Comment by MonzUn** [comment]
Right!
I remember now that this is what I originally wanted to do. I couldn't find how to properly cast stuff to access that info though.

I will be able to solve that by looking at the code soon.
I will replace the owner name with the store name :)

**Comment by MonzUn** [comment]
Trade feed now references the store name instead of the store owner name. This fix will be in the next feature update.
