### ISSUE TITLE
[FEATURE REQUEST] Discord Demographics

### ISSUE THREAD

**Issue by xtreampb** [Eco-DiscordLink/EcoDiscordPlugin#23]
Have a default demographics created from discord roles.  These demographics shouldn't take up space in civic objects.  This should behave similarly to the built in active, abandoned, and admin demographics that already exists.

It was stated that there was a dependency on a user connection between eco and discord accounts.

original discord request: https://discord.com/channels/617269603093053440/741591917321519206/768461926736723988

**Comment by MonzUn** [comment]
I'm not entirely sure that this can be done. I'll need to look into how those special demographics work.
I would also like to make this work the other way around, so that you can set up ingame demographics to translate into roles.

**Comment by xtreampb** [comment]
The reason for wanting to import discord roles is that i can give discord members demographics in the server and certain perks.  Like if people wanted to decide what jobs (like food, smithing ect) between resets.  the discord roles would survive past server resets/restarts.

**Comment by MonzUn** [comment]
After recently looking into other features related to demographics I also had a look at this one.

It seems overly complex and messy to maintain and would also require some hacky solutions to begin with.

At the same time the civics exporter solves most of the same problem.
