### ISSUE TITLE
Add: search by tag

### ISSUE THREAD

**Issue by StefArma** [Eco-DiscordLink/EcoDiscordPlugin#28]
/dl-trade furniture 

improvement: separate the sales from buy
/dl-trade-sell furniture 
/dl-trade-buy furniture 

godlike: add custom tag
/dl-trade-sell furnitureT3

**Comment by MonzUn** [comment]
This code hasn't been updated since tags were introduced and I agree, this would be a natural upgrade and quite useful.
I'll try to get this updated for a future update. Probably not the next one as to not incur more feature creep, but probably the one after that.

**Comment by MonzUn** [comment]
Tag based search has been implemented.
Separate Buy/Sell will be done later.
Custom tags will not be possible.
