### ISSUE TITLE
Loggfiles does not been stored in the correct folder

### ISSUE THREAD

**Issue by Bullhill** [Eco-DiscordLink/EcoDiscordPlugin#29]
On linux servers the logfiles is stored under the name 'ecoserver\Mods\DiscordLink\Pluginlog.txt'
Not as Pluginlog.txt in the folder "ecoserver\Mods\DiscordLink\"

Linux is using \ as an escape char and not folder, need to use / to define folders

**Comment by MonzUn** [comment]
Ah! My bad.

I have no Linux setup to test on, but I will switch around the / to get it right.
Thanks for the report!

**Comment by MonzUn** [comment]
I haven't been able to test this on Linux, but I have changed the \\ to / in the base path used for pointing to the mod dir.
