### ISSUE TITLE
[2.1.1] Election Events not following Anonymous Voting Setting

### ISSUE THREAD

**Issue by NHDriver4** [Eco-DiscordLink/EcoDiscordPlugin#33]
The election events feed is not honoring the Anonymous Voting setting on the server and shows in discord who voted which way. 

![image](https://user-images.githubusercontent.com/49725/107800069-519a7e00-6d2c-11eb-87ca-e3ae2400df6c.png)
![image](https://user-images.githubusercontent.com/49725/107800132-66771180-6d2c-11eb-9cf5-78628b3b3f65.png)

**Comment by MonzUn** [comment]
Thanks for the report! I just haven't taken this into consideration. I'll try to get it into the 2.2.0 release!

**Comment by MonzUn** [comment]
The election display will now state that the votes are anonymous.
This will be in version 2.2.0.
