### ISSUE TITLE
Add Activity String

### ISSUE THREAD

**Issue by MonzUn** [Eco-DiscordLink/EcoDiscordPlugin#34]
Display player count, time left, or similar information in the bot users rich presence string.

**Comment by Dave247** [comment]
Just a heads up that I left this as a suggestion on the the game's suggestion tracker (StrangeLoopGames/EcoSuggestions/issues/1415), in case the developers implement this themselves at some point.

**Comment by MonzUn** [comment]
Yeah, that's another thing actually.
What Discord calls rich presence and what Steam calls rich presence seem to be different things.

What I want to add is the activity text.
So these two tickets are actually targeting different (although related) things :)

**Comment by Dave247** [comment]
Ah that makes a lot more sense as I thought it was kinda weird, you're only affecting the bot and not a individual users status as that would likely require a whole different thing.

**Comment by MonzUn** [comment]
Even added some flavor texts for when the server is empty =)
