### ISSUE TITLE
ECO MOD (discord mod)

### ISSUE THREAD

**Issue by Boxerlewy** [Eco-DiscordLink/EcoDiscordPlugin#35]
I can see you have displayed instructions on how to do this if you have the server on your computer. I'm using GTX gaming and I pay them how would I go about doing it there?

Also, could anyone tell me where do I input the code to make chat colour different for mods?

I'm sorry if I seem a bit of a boomer I'm just new to all this sort of stuff so thanks in advance anyone :-)

**Comment by MonzUn** [comment]
Hi, the development of this mod has moved to here 
https://github.com/Eco-DiscordLink/EcoDiscordPlugin

If you want support with setting it up, you can reach me on in the DiscordLink channels on this Discord Server.
https://discord.gg/pCkWfzQ
