### ISSUE TITLE
Add event notifications for server starting/stopping

### ISSUE THREAD

**Issue by szalkerous** [Eco-DiscordLink/EcoDiscordPlugin#39]
Add in event notifications for when the server starts up and for when it shuts down to let people know on Discord if the server is online.

For example, the Discord plugin for Space Engineers uses the following:

```
  <Started>:white_check_mark: Server Started!</Started>
  <Stopped>:x: Server Stopped!</Stopped>
```

**Comment by drkshrk** [comment]
To add onto that maybe include the server name / ip or an option to at least for servers with multiple servers sharing the same channel for that info

**Comment by MonzUn** [comment]
Thanks for the suggestion!

I can sort of do this.
I can however only see when the plugin starts and stops (I can filter out restarts), not when the server starts or stops, so any timestamp would be slightly off and it wouldn't be possible to check anything retroactively. This means that if the server stops in a non graceful manner, it wouldn't be possible to add this to the log.

@drkshrk Good point!
I can do it as an embed and use the standard footer. That will give timestamp and server name.

**Comment by MonzUn** [comment]
I felt inspired, so I made this during my lunch :P
![image](https://user-images.githubusercontent.com/11805935/109638952-e683e080-7b4e-11eb-93da-04d2ffed10ab.png)

**Comment by MonzUn** [comment]
Implemented - Will be included in the next feature release!

Feel free to add comments if you have more input on this feature :)

**Comment by szalkerous** [comment]
> I can however only see when the plugin starts and stops (I can filter out restarts), not when the server starts or stops, so any timestamp would be slightly off and it wouldn't be possible to check anything retroactively. This means that if the server stops in a non graceful manner, it wouldn't be possible to add this to the log.

This is to be expected, there's no way a hosted plugin can determine if the server is running if the plugin itself is not executing, without getting into the messy need for an external process to be running. I think most people can live with that.

> 
> 
> Implemented - Will be included in the next feature release!
> 
> Feel free to add comments if you have more input on this feature :)

Well done! If you want extra polish, you can make a new line in the status display module to indicate when the server started or stopped. "Online since ...." and "Offline since...", simple as just caching the timestamp on startup, and when it goes down you can overwrite the stamp and push one last message update. That is, however, simply icing on the cake. You already took care of the important part!

Thank you!

EDIT: You can also tap the unused potential of the bot status text in Discord, the area where "Playing Eco" or "Away", etc. would be displayed for a typical user. I know the Space Engineers plugin uses it to show players online and sim speed (server health), but your plugin could use it for anything, even just the aforementioned "Server Online", "Server Offline" or whatever.

**Comment by MonzUn** [comment]
Thanks! I recently added those timestamps to the Server GUI Display. I could add them to the server info as well!

The rich presence there is already a ticket for :)
Don't know if I want to have the online status there though. Might get iffy with mismatched states.
Player count or other things are probably more interesting to show.
