### ISSUE TITLE
Add command versions of existing Displays

### ISSUE THREAD

**Issue by MonzUn** [Eco-DiscordLink/EcoDiscordPlugin#40]
This would be helpful for servers that don't want to run displays but still want this information.

**Comment by Dave247** [comment]
It could also help to reduce some of the constant traffic between the game server Discord by only having the information sent over when it is requested, though I don't know if this would realistically have any effect on anything.

The main point of this is to prove a more on-demand alternative compared to having a constant static block.

**Comment by MonzUn** [comment]
It may have an effect. It depends on what and how many features are enabled and what their load is. It also very much depends on what load Discord is seeing overall on the server your Guild is in.

**Comment by MonzUn** [comment]
Command versions of all current displays are now available.

This change will be included in the next feature update.
