### ISSUE TITLE
Add feed for the beginning/end of elections

### ISSUE THREAD

**Issue by Dave247** [Eco-DiscordLink/EcoDiscordPlugin#41]
As a more on-demand alternative to having the elections be a part of the display module, you could have it so a message is sent into a Discord channel whenever a new election is started, and another message when the election is over that lists the results (if it passed or failed).

I believe this should also be able to tie into the planned feature (#7) of allowing users to vote in elections through Discord using emotes, due to it's semi-static nature.

Compared to being a constant update ticker as a display, the intent of having it as a feed would be to act as more like a record/notification of elections. Once the bot would post a message there wouldn't need to be any other action taken by the bot/mod, except maybe for editing the election start message to note the election is now over and/or link to the election ended message.

**Comment by MonzUn** [comment]
Sounds like a great and hopefully (depending on what hooks exist in the server) easy to implement feature!

I don't understand how it ties into #7 though?

**Comment by MonzUn** [comment]
I have implemented this feature and it will be included in the next feature release.

**Comment by Dave247** [comment]
> Sounds like a great and hopefully (depending on what hooks exist in the server) easy to implement feature!
> 
> I don't understand how it ties into #7 though?

Ah sorry I thinking back to the discussion we had on Discord when I was typing this, where you said how if you were to make this into a command it wouldn't work with how you plan to implement voting with embeds , which I assumed would be referring to that ticket, and that it still would be able to be implemented by doing it this way instead.
