### ISSUE TITLE
Feature Request: User Stats Command

### ISSUE THREAD

**Issue by CKades** [Eco-DiscordLink/EcoDiscordPlugin#43]
Would like the DiscordBot to be able to pull a report on user stats

?dl-userstats (Everyone)

Everyone or 

?dl-userstats "EcoUser1"

Example:
Username: Ecouser1
Skills:
Smiting: Level 3
Campfire Cooking: Level 4
Player Level:
Star Level: Level 4

**Comment by MonzUn** [comment]
I would probably limit this to single users or possibly demographics.

Otherwise all the messages required to send it to Discord could start throttling everything.

**Comment by MonzUn** [comment]
This has been implemented and will be in the next feature release.
It will include information in the following areas:
- Online Status
- PlayTime
- Permissions
- Access Lists (Whitelist, ban, mute)
- Discord Info (if linked => Name, join date etc)
- Reputation (Only totals. Individual was not possible due tor restrictions in the modkit)
- XP
- Skills
- Demographics
- Titles
- Deeds
