### ISSUE TITLE
Feature Request: Currency report command

### ISSUE THREAD

**Issue by CKades** [Eco-DiscordLink/EcoDiscordPlugin#44]
Currency Report:

?dl-currency "Dollars"

Example
Currency is Dollars

Total Currency: Dollars, $100,000
User1, Dollars, $100
User2, Dollars, $55.24
Treasury, $Dollars, $80,000

?dl-richest "Dollars"

Example
Currency is Dollars

Total Currency: Dollars, $100,000
Treasury, $Dollars, $80,000
User1, Dollars, $100
User2, Dollars, $55.24

**Comment by MonzUn** [comment]
This is a neat extension to the functionality which drives the currency display.

**Comment by MonzUn** [comment]
Currency reports via commands for individual and all currencies have been implemented for Eco and Discord.
