### ISSUE TITLE
Crash in work party display data fetching

### ISSUE THREAD

**Issue by CKades** [Eco-DiscordLink/EcoDiscordPlugin#45]
Oddly after a reboot i'm always getting this as a failure with the DiscordLink, had to remove the mod from the modfolder to keep the server going.

--BEGIN DUMP--
Dump Time
04/02/2021 18:16:22

Exception
Exception: NullReferenceException
Message:Object reference not set to an instance of an object.
Source:DiscordLink

System.NullReferenceException: Object reference not set to an instance of an object.
   at Eco.Plugins.DiscordLink.Modules.WorkPartyDisplay.GetDisplayContent(DiscordTarget target, List`1& tagAndContent)
   at Eco.Plugins.DiscordLink.Modules.Display.UpdateInternal(DiscordLink plugin, DLEventType trigger, Object data)
   at Eco.Plugins.DiscordLink.Modules.Module.Update(DiscordLink plugin, DLEventType trigger, Object data)
   at Eco.Plugins.DiscordLink.DiscordLink.<>c__DisplayClass57_0.<<UpdateModules>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

--END DUMP--

**Comment by CKades** [comment]
incase it's needed, i do use other mods:
![image](https://user-images.githubusercontent.com/72682200/113443617-57255380-93c0-11eb-8d46-b5d92bc27821.png)

**Comment by CKades** [comment]
Looking at the build i'm using; DiscordLink2.2.0
![image](https://user-images.githubusercontent.com/72682200/113443838-b7b49080-93c0-11eb-90bc-c7c5a10a1cf3.png)
Was wondering if this could be the problem.

**Comment by MonzUn** [comment]
Could you supply the server or plugin log and a copy of your config with the bot token obfuscated?

I've fixed an issue with this before and I suspect it might be a similar thing. Some work party might have broken in the restart and now DL crashes when it reads the broken work party.

It's my guess at least.

**Comment by CKades** [comment]
Per-request
Work parties:
![image](https://user-images.githubusercontent.com/72682200/113456725-0c193980-93dc-11eb-8ee1-2486aef80a7e.png)

[DiscordLink.txt](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/files/6251362/DiscordLink.txt)
[Pluginlog.txt](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/files/6251363/Pluginlog.txt)

**Comment by MonzUn** [comment]
This issue occurs when Discord is being slow to respond.
It's a secondary effect of it as Work Parties will cause a crash if there is an invalid channel link for them in 2.2.1 and it is invaliud because Discord is being slow in suppling the bot with the guild information.

This is already fixed in 2.3.
