### ISSUE TITLE
Admin roles config does not accepts IDs

### ISSUE THREAD

**Issue by MrWhiteFlamesYT** [Eco-DiscordLink/EcoDiscordPlugin#46]
Hello developers
Would like to have it be able to use ID's as well, cause everything ells does use id's. cause case sensitive is good but easy to break too.
Kind regards
MrWhiteFlamesYT

**Comment by MonzUn** [comment]
Hello user!
I shall make this for the reasons you so excellently laid before me!

**Comment by MonzUn** [comment]
Admin roles now accept IDs as well.
The fix will be included in a future update.
