### ISSUE TITLE
Feature Request: Server Shutdown through Discord

### ISSUE THREAD

**Issue by drkshrk** [Eco-DiscordLink/EcoDiscordPlugin#47]
- Discordbot would receive a command through discord from an authorized role that would trigger the eco server to shutdown.
  - Server - depending on the command would immediately save and shut down or send an in-game message/announcement that the server will reboot/shut down in x minutes.

Would be helpful for minor updates that don't break everything if you are on the road to trigger a reboot which would then let the server update.

**Comment by MonzUn** [comment]
I'll have a look and see if this is possible :)

**Comment by Dave247** [comment]
Maybe through an RCON command? Otherwise I can't think of any existing solutions that you could easily tap into, aside from possibly the auto-shutdown feature, but even that would likely require having to dig into the game's source code to discover exactly how it does it.

**Comment by MonzUn** [comment]
Added a ServerShutdown command. This will be released in version 3.3.0
