### ISSUE TITLE
DiscordLink is incompatible with Eco 9.3.x

### ISSUE THREAD

**Issue by RuffKez21** [Eco-DiscordLink/EcoDiscordPlugin#48]
Hey, 
i setted everything up correctly and I always get Errors thrown by the Plugin:

```
[06:49:20] [DiscordLink] Plugin version is 2.2.1
[2021-04-22 06:49:21 +02:00] [102 /ConnectionFa] [Error] Connection attempt failed, retrying in 7s
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.WebSockets.Client, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Net.WebSockets.Client, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DSharpPlus.Net.WebSocket.WebSocketClient.ConnectAsync(Uri uri)
   at DSharpPlus.DiscordClient.InternalConnectAsync()
   at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable`1 status, Nullable`1 idlesince)
```

I think I'm missing a depency but couldn't find one. Might be dotNet feature?
Is there a workaround for linux mashines?

Kind regards,
Kez

**Comment by drkshrk** [comment]
This is a know issue with the current Eco version.  They are changing the base game to target a new framework and it is causing a conflict with a dependency on this mod.

For right now unfortunately you can't use DL with the current eco.

**Comment by MonzUn** [comment]
This turned out to be an issue with the Eco server package rather than DiscordLink.

There is a pull request targeting the next release so hopefully 9.3.4 will enable DL to be loaded again.

I'll update here as new information is available.

**Comment by MonzUn** [comment]
The fix for this issue has been merged into the release branch of Eco, so it should be coming with the next release.
I've tested DiscordLink 2.2.1 with Eco 9.3.3 and it seems to work fine, so no update of DiscordLink should be necessary.

**Comment by MonzUn** [comment]
Version 2.2.1 should now work again as Eco 9.3.4 has been released with a fix for the issue that was breaking DiscordLink.
