### ISSUE TITLE
[2.3 Preview] Server Info Display missing newlines

### ISSUE THREAD

**Issue by drkshrk** [Eco-DiscordLink/EcoDiscordPlugin#53]
![2021-05-10 10_27_47-eco-status](https://user-images.githubusercontent.com/2175749/117675319-757a2e00-b17a-11eb-88f0-f3d666729587.png)

Active Elections - Formatting for Votes & Time Remaining.  All elections are on 1 line.

**Comment by MonzUn** [comment]
Meh, missed so many \n when I did this ^^'

**Comment by drkshrk** [comment]
That's ok - these are the easy ones to fix!  If I didn't spend so much of my free time playing I know I could fix this one hahah
