### ISSUE TITLE
[2.3 Preview] Footer falls off Status on Updates

### ISSUE THREAD

**Issue by drkshrk** [Eco-DiscordLink/EcoDiscordPlugin#55]
Footer seems to appear on first posting but falls off on the status updates
![image](https://user-images.githubusercontent.com/2175749/118324572-39273480-b4d0-11eb-9059-3d8314480557.png)
Above Image is after an update.
Below is First Posting after deleting content from Discord.
![image](https://user-images.githubusercontent.com/2175749/118324748-7095e100-b4d0-11eb-98f8-1c41b1582799.png)

**Comment by MonzUn** [comment]
What's your min size embed config at?On May 14, 2021 22:22, Joe ***@***.***> wrote:
Footer seems to appear on first posting but falls off on the status updates

Above Image is after an update.
Below is First Posting after deleting content from Discord.

**Comment by MonzUn** [comment]
What is your min size for embed footers at in the config?

**Comment by drkshrk** [comment]
I changed it to small and that's what was happening.  Before that at medium it wasn't showing at all or it was doing the same thing.  I know at medium the footer wasn't in the join/leave message but it is since i moved to small it now shows in there.

**Comment by MonzUn** [comment]
It should show on all sizes above the one you select. So on medium, it should show on medium and large sizes.
Is that not the behavior you're having?

**Comment by drkshrk** [comment]
So based on the photos that's is what I am getting.  The status feed the first time it posts if there's nothing there it adds the footer.  When it updates it removes the footer.  I would expect if the footer shows the first time it would show after the updates at well?

I think I wasn't understanding the "size" and what that means in correlation to when it should show as a side note.  So it's based on the size of the embed?

**Comment by MonzUn** [comment]
Ah, then I understand what the bug is. It's not there consistently

What do you feel is missing in the description of the setting?
> Determines for what sizes of embeds to show the footer containing meta information about posted embeds. All embeds of sizes bigger than the selected one will have footers as well.

It's technically based on the number of fields in the embed.
