### ISSUE TITLE
[2.3 Preview] dl-link says it doesn't have server members intent even when it does

### ISSUE THREAD

**Issue by drkshrk** [Eco-DiscordLink/EcoDiscordPlugin#56]
Claims to not have Server Members Intent even though the bot has it.  Prevents DL-LINK feature from working.

**Comment by MonzUn** [comment]
I've looked into this and it seems to be an issue with DSharp. I'll see if there is an update or check with their Discord.

**Comment by MonzUn** [comment]
I've found the cause of the issue.
It's a change in DSharp that now requires you to state the intents when the client is created.
I'll have to refactor some of of the setup logic to be able to handle users not having the intents set properly.
