### ISSUE TITLE
[2.3 Preview] Server Info - Active Election Time remaining 

### ISSUE THREAD

**Issue by drkshrk** [Eco-DiscordLink/EcoDiscordPlugin#57]
As can be seen in the screen shot - Time remaining on the Active elections is adding a "-" sign before each number.  

Also the maximum width of the field is causing text wrapping which is causing it to go out of alignment with the Active Elections text.

![image](https://user-images.githubusercontent.com/2175749/118325371-5e687280-b4d1-11eb-98bb-0d72baf3f9d8.png)

**Comment by drkshrk** [comment]
I just realized elections only go for 24 hours... There is currently 1-Hour 7-Minutes but the dl bot says its -7 Days, -6 hours, -44 minutes at the moment.

**Comment by MonzUn** [comment]
This has been resolved.
