### ISSUE TITLE
Bot says command channel is not command channel, shows dev ID for the same 

### ISSUE THREAD

**Issue by kotoroshinoto** [Eco-DiscordLink/EcoDiscordPlugin#64]
copied the channel ID: 925870515334295592

tried ?ping

bot replied with:

"You aren't allowed to post commands in this channel.
Commands are allowed in the following channels:
- 925870515334295592"

**Comment by MonzUn** [comment]
Did you run the command in the command channel?

**Comment by kotoroshinoto** [comment]
yes

**Comment by MonzUn** [comment]
Could you try it using names instead of ID?

I have fixed some issues for 3.0 where channel IDs weren't properly checked.

**Comment by MonzUn** [comment]
Closing due to lack of response and that the upcoming release of 3.0 should solve this issue.
