### ISSUE TITLE
Add override variable for WebServerAddress port

### ISSUE THREAD

**Issue by Asharas** [Eco-DiscordLink/EcoDiscordPlugin#76]
Hi!

I noticed the web URL displayed by the bot server-info module concatenates the port and path to set string. 

In my humble opinion this should get an override variable, eg I have a reverse proxy in front of Eco's web server so I can serve it with TLS (as every responsible admin should do).  

The workaround is trivial, just tell my reverse proxy to listen on that port, but it's a bit of an ugly bandaid.  

I hope you'll consider this request :)

**Comment by MonzUn** [comment]
Hi, the override that DL has in 3.0 is redundant with the vanilla network config.
I've removed it for 3.1, so it's not an issue there :)

**Comment by Asharas** [comment]
Thanks, I'll close the issue then.  

Also, just for more context, the reverse proxy listens on standard HTTP/HTTPS ports and allows me to set TLS so the website is safely reachable from the domain name only.
