### ISSUE TITLE
[0.9.7.6] Lost messages with multiple linked duplex chat channels.

### ISSUE THREAD

**Issue by Dave247** [Eco-DiscordLink/EcoDiscordPlugin#83]
When using more than a single synchronised duplex chat channel, messages sent from Discord do not appear to be sent to the linked in-game channel, while messages from the game will still be sent to Discord.
For example, linking the general channel, and then at least one other custom created chat channel in-game, with each linked to a separate Discord channel.

Perhaps this has something to do with the push to dot.net 7 that SLG did?

Link to discussion on the Eco Modding Discord for original reference: https://discord.com/channels/617269603093053440/741600871745454133/1061982457743806504

**Comment by MonzUn** [comment]
I've set up the same case as you have in your config on my test server and everything works as expected.
I'm going to need more information on how to reproduce this issue.

**Comment by Dave247** [comment]
Apologies I saw your reply but completely forgot about it.
I've gone back to try it again today by adding back the same configuration I originally used with multiple channels, and the same issue occurred, however I noticed that it was only in the additional channels that messages were not being sent to the game, while the general chat still worked as intended.

Both additional channels in Discord are set to private channels need a role to be seen however, so I am thinking that maybe it has something to do with permissions maybe, except I would expect that to more be the case if it the bot couldn't post to Discord, not the other way around?

The only other thing I can think of that is worth mentioning, is if I try running the `?Echo` test in one of the additional chat channels, that the output instead comes though the default general channel which seems odd, though I'm unsure if it is related or not.

**Comment by Dave247** [comment]
So I set my my own test enjoinment with a clean local Eco server and a newly created Discord server and had all three channels that I created worked as intended, so I guess it is probably a permission issue, but I'll be damned trying to figure out what exactly does cause it, as I can't think of anything else to try to test.

Also the `Echo` command still only default to the general channel so that does seem to just be an unrelated oversight.

**Comment by MonzUn** [comment]
The `Echo` command has a parameter for which Eco channel it should send to.
Nevertheless, I've now improved it to use any linked channel to the sender channel if available.

**Comment by Dave247** [comment]
> The `Echo` command has a parameter for which Eco channel it should send to. Nevertheless, I've now improved it to use any linked channel to the sender channel if available.

Ah my expectation would be that if I use the command in a chat channel then it would send and receive from the that channel, but I forgot how the typical intended usage is being able to use commands in any chanel.
