### ISSUE TITLE
Dosent work with active firewall

### ISSUE THREAD

**Issue by BladeRavinger** [Eco-DiscordLink/EcoDiscordPlugin#85]
I have a dedicated server with firewall, all the ports for the game and other connections i need are open but while the firewall is active Discord link dosent work, what protocol/port does the link use so that i can give it access through the firewall, 

isit a range? can you add a config to select a port?

**Comment by MonzUn** [comment]
I asked the DSharp developers and got this response:
![image](https://user-images.githubusercontent.com/11805935/216815535-3308818d-9818-420a-8f02-636ad8f75a48.png)

Your problem does not lie with DiscordLink so I will be closing the issue.
