### ISSUE TITLE
wtPlatest/update 10 compatability

### ISSUE THREAD

**Issue by primo4e** [Eco-DiscordLink/EcoDiscordPlugin#90]
I attached the log from my server when trying to launch with discordlink installed. IT boots normally without discordlink
 
[log_230719022312.log](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/files/12099835/log_230719022312.log)

**Comment by MonzUn** [comment]
You are using an outdated version.
The main branch is updated and works for version 10, but there won't be a release until SLG makes an official release of version 10, so if you want to run DisocrdLink on version 10, you'll have to compile it yourself.

**Comment by primo4e** [comment]
Okay thank you.
