### ISSUE TITLE
Discord connection failed

### ISSUE THREAD

**Issue by Nick1Z2** [Eco-DiscordLink/EcoDiscordPlugin#91]
Hello, I've set everything as in "Installation.md" but when I start or restart I always get errors

[ Info] DiscordLink Restarting... 
[ Info] DEBUG: Attempting plugin restart 
[ Info] DEBUG: Discord Client status changed from "Discord connection failed" to "Restarting..." 
[ Info] DEBUG: Client Starting 
[ Info] DEBUG: Discord Client status changed from "Restarting..." to "Creating Discord Client" 
[ Info] DEBUG: Discord Client status changed from "Creating Discord Client" to "Connecting to Discord..." 
[Error] Bot application is not configured to have the required intents. See install instructions for help with adding intents. 
[ Info] DEBUG: Discord Client status changed from "Connecting to Discord..." to "Discord connection failed" 

[11] [ Info] [Eco] [DiscordLink] DiscordLink Restarting... 
[139] [ Info] [Eco] [DiscordLink] Bot application is not configured to have the required intents. See install instructions for help with adding intents. 
[11] [ Info] [Eco] [DiscordLink] DiscordLink Restarting... 
[141] [ Info] [Eco] [DiscordLink] Bot application is not configured to have the required intents. See install instructions for help with adding intents.

**Comment by MonzUn** [comment]
Hello, could you double checked that you performed step 15 correctly?
![image](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/assets/11805935/973403b9-3e26-4164-a837-99c1228d1833)

**Comment by Nick1Z2** [comment]
Hello, I checked again and I was actually sure that I did it, but apparently the setting wasn't accepted, I tried it right away and it works. Thanks
