### ISSUE TITLE
Chat sync (optin) resets every restart or when players logout and back in.

### ISSUE THREAD

**Issue by Travistbh** [Eco-DiscordLink/EcoDiscordPlugin#93]
Players have to optin every time they login to the server.  I am not sure if this was intended but is there a way to save the players optin settings to the server?

**Comment by MonzUn** [comment]
That's odd. I'll do some tests this weekend if I get the time (it's a bit hectic at the moment).
Had a quick look at the code now and it should be stored in Storage/Mods/DiscordLink/PersistantData.json

**Comment by Travistbh** [comment]
I thought so as well,  and i checked, the moment users opt in  their info is recorded however the file keeps being overwritten,   
leading to players having to optin again when they log back in

**Comment by MonzUn** [comment]
Thanks, with that info in mind I think I have a suspect! Might get time to look at it tomorrow.

**Comment by Travistbh** [comment]
No worries, I did confirm the file is not properly saving/updating and resets after a restart.

**Comment by MonzUn** [comment]
I've made a fix. It will be deployed when I've fixed some other things and tested on my own server :)
Thanks for the report!

**Comment by Travistbh** [comment]
If you need testing let me know

**Comment by MonzUn** [comment]
Thanks! It was an easy fix when I found it though. Nothing in persistent data storage was being read ^^'

Should have a patch out in a few days :)

**Comment by Travistbh** [comment]
Wanted to let you know that the optin issue has come back,   it works when players logout and in but is being overwritten on restart only this time, this may be something with my host however i cannot confirm that.   my recommendation is default optin and give them the option to optout (flip flop the options)
