### ISSUE TITLE
[Error] DSharpPlus.Exceptions.NotFoundException: Not found: 404

### ISSUE THREAD

**Issue by CappyTech** [Eco-DiscordLink/EcoDiscordPlugin#99]
```
 [Error] Error occurred when attempting to read message with ID 1215012100263510036 from channel "currency"
Exception: DSharpPlus.Exceptions.NotFoundException: Not found: 404
   at DSharpPlus.Net.DiscordApiClient.GetMessageAsync(UInt64 channel_id, UInt64 message_id)
   at DSharpPlus.Entities.DiscordChannel.GetMessageAsync(UInt64 id, Boolean skipCache)
   at Eco.Plugins.DiscordLink.DiscordClient.GetMessageAsync(DiscordChannel channel, UInt64 messageID)
```
![Screenshot 2024-03-09 212327](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/assets/133281784/2829afc2-c77a-4f2d-83a8-2b80848f0c00)

**Comment by CappyTech** [comment]
Discord Permissions for Currency channel: 
![Screenshot 2024-03-09 212540](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/assets/133281784/47ea75d7-fc03-44de-876e-c1d088dea1d3)

Discord Permission for Category:
![Screenshot 2024-03-09 212623](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/assets/133281784/d7990909-7a00-438e-a524-eb6a0daea5a1)

Discord Permission for Bot:
![Screenshot 2024-03-09 212708](https://github.com/Eco-DiscordLink/EcoDiscordPlugin/assets/133281784/af10a797-68c8-42a3-941b-3d2c02ed4097)

**Comment by JulianMa** [comment]
@CappyTech can you please run the following commands:
```
/verifypermissions
/verifyserverpermissions
/verifychannelpermissions
```
And report the output?

**Comment by JulianMa** [comment]
The Exception you posted has also nothing to do with the currency linking.

**Comment by MonzUn** [comment]
Closing due to lack of response from author.
